version: '3'
services:
  db:
    image: postgres:12.0-alpine
    # restart: always
    environment:
      POSTGRES_USER: alexey
      POSTGRES_PASSWORD: example
      POSTGRES_DB: onlinesimcard
    # volumes:
    # - onlinesimcard:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build: ./
    image: 23091996/onlinesim_api_klc4f9j40dfk4f8hdfk04fj
    ports:
      - '4500:4500'
# volumes:
# onlinesimcard:
