export enum SmsActivationStatus {
  STATUS_WAIT_CODE = 'STATUS_WAIT_CODE',
  STATUS_WAIT_RETRY = 'STATUS_WAIT_RETRY',
  STATUS_CANCEL = 'STATUS_CANCEL',
  STATUS_OK = 'STATUS_OK',
  ACCESS_CANCEL = 'ACCESS_CANCEL',
  WRONG_ACTIVATION_ID = 'WRONG_ACTIVATION_ID',
}
